### ISSUE TITLE
[question] Issues while installing

### ISSUE THREAD

**Issue by hlegius** [kiambogo/scrava#13]
Hello there!

I am trying to pull in following the `ProjectRef` or `ProjectRoot` idea found out there, but it says there is no artefact available and therefore, fails due unsolved dependencies.

I've searched on MavenCentral, but there is no package there. How's the best way to install it?

I am using latest sbt and Scala version (0.13.13/2.12.1) on a brand new (pet)project.

Thanks in advance!

**Comment by kiambogo** [comment]
Hi @hlegius. Thanks for opening an issue.

As this project is gaining more traction, I believe it would be helpful to release it on Maven - I've created https://github.com/kiambogo/scrava/issues/14 to track that work. 

In the meantime, the standard way of using this library is to build the jar yourself. You can do this by getting the source code (https://github.com/kiambogo/scrava/releases) and compiling the jar with `sbt package`. This will package up a jar for you in `scrava/target/scala-2.11/`. You can then use this in your project by including it in your build path. 

Hope that helps you out - let me know if you need further assistance. Thanks for your interest in this project!

**Comment by kiambogo** [comment]
I've deployed the project on Maven Central and updated the readme
