### ISSUE TITLE
Fix segmentExplorer and add Integration Test

### ISSUE THREAD

**Issue by elcurto99** [kiambogo/scrava#8]
I was working with your Strava Client, and I noticed that the ScravaClient::segmentExplorer function was not working. Secondly, I also noticed it wasn't covered by an integration test.

I worked though it last night, so I should be able to send you a pull request with both of these resolved once I separate these changes from my own project.

Also, thanks for creating this! You saved me tons of time/work.

**Comment by kiambogo** [comment]
Hey @elcurto99, thanks for opening an issue and bringing this up! When I initially built this I was building it around my use case which meant that outside of some unit tests I didn't properly test out all the endpoints in depth..so thanks for pointing out this bug :)

A PR would be awesome! Glad to hear that this project has been able to save you some time and work - always happy to hear that people are able to benefit from it.
